// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/aftouh/k8s-sample-controller/pkg/apis/team/v1"
	"github.com/aftouh/k8s-sample-controller/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type AftouhV1Interface interface {
	RESTClient() rest.Interface
	TeamsGetter
}

// AftouhV1Client is used to interact with features provided by the aftouh.io group.
type AftouhV1Client struct {
	restClient rest.Interface
}

func (c *AftouhV1Client) Teams(namespace string) TeamInterface {
	return newTeams(c, namespace)
}

// NewForConfig creates a new AftouhV1Client for the given config.
func NewForConfig(c *rest.Config) (*AftouhV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &AftouhV1Client{client}, nil
}

// NewForConfigOrDie creates a new AftouhV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *AftouhV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new AftouhV1Client for the given RESTClient.
func New(c rest.Interface) *AftouhV1Client {
	return &AftouhV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *AftouhV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
