// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/aftouh/k8s-sample-controller/pkg/client/clientset/versioned/typed/team/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAftouhV1 struct {
	*testing.Fake
}

func (c *FakeAftouhV1) Teams() v1.TeamInterface {
	return &FakeTeams{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAftouhV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
