kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aftouh-teams-admin
rules:
  - apiGroups: [""]
    resources: ["namespaces", "resourcequotas"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["aftouh.io"]
    resources: ["teams"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["aftouh.io"]
    resources: ["teams/status"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
